spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        native:
         # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/joao-tinelli/joaobank-config"
          default-label: main
          timeout: 5
          clone-on-start: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enable: true
  endpoint:
    health:
      probes:
        enabled: true
